### ISSUE TITLE
Cannot update jitsu and unable to deploy app

### ISSUE THREAD

**Issue by jeffschwartz** [nodejitsu/jitsu#513]
I tried to deploy my app:
    <code>jitsu deploy</code>

I get the following:
    warn:    A newer version of jitsu is available. please update immediately
    help:    To install the latest jitsu type `[sudo] npm install jitsu -g`
    warn:    To continue without an update type 'yes'
    prompt: Continue without updating? Bad things might happen (no):

Then I run:
    <code>sudo npm install jitsu -g</code>

And I get the following output:
    Password:
    /
    > ws@0.4.32 install /Users/jeffrey/.nvm/v0.12.0/lib/node_modules/jitsu/node_modules/nodejitsu api/node_modules/preacher-api/node_modules/ws
    > (node-gyp rebuild 2> builderror.log) || (exit 0)

```
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.12.0","npm":"2.5.1"})
npm WARN deprecated extendable@0.0.6: This project has been renamed to extendible. This project will not receive any updates anymore
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.12.0","npm":"2.5.1"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.12.0","npm":"2.5.1"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.12.0","npm":"2.5.1"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.12.0","npm":"2.5.1"})
/Users/jeffrey/.nvm/v0.12.0/bin/jitsu -> /Users/jeffrey/.nvm/v0.12.0/lib/node_modules/jitsu/bin/jitsu
jitsu@0.15.0 /Users/jeffrey/.nvm/v0.12.0/lib/node_modules/jitsu
├── opener@1.4.0
├── progress@0.1.0
├── ladder@0.0.1
├── complete@0.3.1
├── spawn-command@0.0.2
├── dateformat@1.0.8-1.2.3
├── flatiron-cli-config@0.1.4
├── semver@1.0.14
├── colors@0.6.2
├── flatiron-cli-users@0.1.10
├── pkginfo@0.3.0
├── canihaz@1.0.1 (which@1.0.8, semver@1.1.4, mkdirp@0.3.5)
├── fstream@0.1.25 (inherits@2.0.1, graceful-fs@2.0.3, rimraf@2.2.8, mkdirp@0.3.5)
├── tar@0.1.18 (inherits@2.0.1, block-stream@0.0.7)
├── fstream-npm@0.1.6 (inherits@2.0.1, fstream-ignore@0.0.10)
├── wizard@0.0.1 (prompt@0.2.14)
├── request@2.42.0 (caseless@0.6.0, json-stringify-safe@5.0.0, aws-sign2@0.5.0, forever-agent@0.5.2, stringstream@0.0.4, oauth-sign@0.4.0, tunnel-agent@0.4.0, qs@1.2.2, node-uuid@1.4.2, mime-types@1.0.2, form-data@0.1.4, http-signature@0.10.1, tough-cookie@0.12.1, bl@0.9.4, hawk@1.1.1)
├── require-analyzer@0.5.0 (eyes@0.1.8, resolve@0.2.8, optimist@0.3.7, read-installed@0.0.4, winston@0.6.2, detective@0.0.4)
├── flatiron@0.3.11 (director@1.1.10, optimist@0.6.0, prompt@0.2.11, broadway@0.2.9)
└── nodejitsu-api@0.6.4 (request@2.25.0, preacher-api@0.1.7)
```

Then when I run <code>jitsu deploy</code> again it again prompts me to update jitsu.

**Comment by 3rd-Eden** [comment]
You can still deploy even if you are presented with an update notification. Just `yes`

**Comment by jeffschwartz** [comment]
That doesn't seem to address the issue of not being able to update jitsu itself. Secondly, by responding yes and the deployment fails for whatever reason it could leave my server fubar.

**Comment by jcrugzz** [comment]
@jeffschwartz this is probably because the path check is looking at an install of `jitsu` that is not under the `nvm` directory. if you installed the latest version using your global version of node rather than the version under `nvm`, i dont think you would have this issue.

**Comment by jeffschwartz** [comment]
@jcrugzz nvm path was the problem. Thanks for the quick turnaround. May I make a small suggestion? Can't jitsu be expanded to test for nvm and if it is being used to use its paths? If that isn't doable then at least couldn't jitsu test for nvm and if it finds it then issue a message something along the lines of "jitsu doesn't currently support nvm paths. Please download and install node v<enter version number here> from nodejs.org, then run "nvm deactivate", and then try running "sudo npm install jitsu -g" again! I think either option would alleviate the confusion one gets when trying to update jitsu blindly fails.

**Comment by Swaagie** [comment]
This is not jitsu not supporting nvm paths. The OS prioritizes the path to the globally installed jitsu (outside nvm). It's not something that would be really useful to add. What we can do is add a answer to the FAQ so people can at least find some references. Depending on what people want they can either delete the globally installed jitsu, usually in `/usr/local/lib/node_modules` and reinstall jitsu using nvm. Or simple change the the alias or symlink to the global jitsu. Personally I'd recommend letting nvm govern all installed global modules.

**Comment by Swaagie** [comment]
https://www.nodejitsu.com/documentation/faq/#does-jitsu-work-with-nvm-
