### ISSUE TITLE
Jitsu should have its own .ignore file

### ISSUE THREAD

**Issue by AvianFlu** [nodejitsu/jitsu#83]
`Jitsu` currently ignores files in a user's `.gitignore` and `.npmignore` files - this can be problematic.  A configuration file full of database credentials and API keys doesn't belong on github, for example, but it definitely belongs in a deployment.  

As a solution, `Jitsu` should perhaps have its own ignore file - `.jitsuignore`?

**Comment by omarmeky** [comment]
How is this feature used?

I added a .jitsuignore file but stuff in my .gitignore file that I need is still not being deployed.
